### ISSUE TITLE
Problem: zgodność formatu danych od hosta dla skryptu analizującego

### ISSUE THREAD

**Issue by kirawasielewska** [kwasielewski/Superfarmer#4]
j.w.

**Comment by elemgie** [comment]
Jaki jest problem? Host podaje kolejność graczy i wypisuje w formacie CSV tak jak opisano w dokumentacji hosta, co zgadza się z założeniami z dokumentacji.

**Comment by kirawasielewska** [comment]
Wszystkie potrzebne informacje są wypisywane - to prawda
Ale sposób formatowania outputu nie zgadza się z istniejącą już implementacją analizy
W folderze Analiza znajduje się opis przejmowanych danych, a w folderze Analiza/Dane przykładowy plik

**Comment by elemgie** [comment]
Zmieniono plik dzialanie_hosta. Wszelkie elementy związane z eksportem danych będą dostosowywane do formatu z folderu Analiza.
