### ISSUE TITLE
Kopiowanie funkcji z innych modułów - BotJP

### ISSUE THREAD

**Issue by elemgie** [kwasielewski/Superfarmer#8]
Pops,
jak chcesz użyć funkcji z innego modułu jeden do jeden to dajesz jej nagłówek po prostu bez definicji. Wszystkie pliki będą kompilowane razem do jednego progrmu wyjściowego, więc Twój kod będzie mógł wywoływać funkcje z innych modułów wewnątrz swoich funkcji (nie wewnątrz maina bo ten może być tylko w jednym module), więc kopiowanie funkcji z modułu do modułu może wywołać konflikty przy kompilacji (tak jakbyś dwa razy inicjalizował jakąś zmienną w jednej funkcji). Najlepiej albo dołączyć nagłówek funkcji i tyle albo, jeżeli chcesz skorzystać z czyjegoś kodu, ale go zmienić, to musisz zadbać aby nazwy funkcji były różne wewnątrz projektu. Znaczy się to wszystko jest to my best knowledge także mogę być w błędzie - trzeba to dokładnie sprawdzić.

**Comment by kirawasielewska** [comment]
+ ta skopiowana funkcja miała w sobie błędy, które teraz są już naprawione, lecz tylko w mojej wersji

**Comment by kirawasielewska** [comment]
Będzie .h
